In [5]:
import torch

torch.__version__

'2.1.0'

In [7]:
t = torch.zeros(2,3,4)
print(t)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
torch.manual_seed(768)


In [9]:
r = torch.rand(3,4)
r2 = torch.rand(3,4)

In [10]:
print(r)
print(r2)

tensor([[0.9827, 0.1657, 0.4688, 0.6988],
        [0.8622, 0.0763, 0.0937, 0.6115],
        [0.4748, 0.3492, 0.1464, 0.9127]])
tensor([[0.5522, 0.1142, 0.8497, 0.6751],
        [0.5858, 0.1434, 0.3115, 0.1251],
        [0.4849, 0.3378, 0.3834, 0.0108]])


In [11]:
torch.manual_seed(768)
r3 = torch.rand(3,4)
r4 = torch.rand(3,4)

print(r3)
print(r4)

tensor([[0.9827, 0.1657, 0.4688, 0.6988],
        [0.8622, 0.0763, 0.0937, 0.6115],
        [0.4748, 0.3492, 0.1464, 0.9127]])
tensor([[0.5522, 0.1142, 0.8497, 0.6751],
        [0.5858, 0.1434, 0.3115, 0.1251],
        [0.4849, 0.3378, 0.3834, 0.0108]])


In [12]:
print(id(r),id(r2))

4831726000 4831728496


In [13]:
print(id(r3),id(r4))

4395906352 4831734928


In [15]:
r.dim()

2

In [16]:
r.shape()

TypeError: 'torch.Size' object is not callable

In [17]:
r.shape

torch.Size([3, 4])

In [21]:
multi_dim = torch.rand(2,3,4,5)
multi_dim.shape
multi_dim.ndim

4

In [22]:
multi_dim

tensor([[[[0.8876, 0.0582, 0.7309, 0.0427, 0.7058],
          [0.5788, 0.3605, 0.1971, 0.2515, 0.8551],
          [0.3536, 0.8667, 0.3235, 0.7239, 0.0895],
          [0.9327, 0.1189, 0.9842, 0.9028, 0.4418]],

         [[0.3228, 0.1289, 0.7725, 0.0839, 0.4225],
          [0.0651, 0.9845, 0.1520, 0.9040, 0.4994],
          [0.9057, 0.2188, 0.8337, 0.3603, 0.2706],
          [0.1558, 0.6337, 0.5682, 0.2261, 0.8841]],

         [[0.2799, 0.0399, 0.6422, 0.0577, 0.0246],
          [0.9265, 0.5851, 0.4744, 0.3165, 0.0961],
          [0.8933, 0.7144, 0.9345, 0.7588, 0.7181],
          [0.0901, 0.8411, 0.4571, 0.8156, 0.1669]]],


        [[[0.4853, 0.3305, 0.7507, 0.9261, 0.1614],
          [0.4535, 0.9071, 0.9215, 0.3729, 0.9477],
          [0.2472, 0.8259, 0.3284, 0.8506, 0.6598],
          [0.5551, 0.6201, 0.4014, 0.1175, 0.4546]],

         [[0.6148, 0.5477, 0.5799, 0.3120, 0.7705],
          [0.2714, 0.1759, 0.3447, 0.8331, 0.7973],
          [0.1136, 0.1700, 0.4861, 0.0683, 0.3890],
  

In [24]:
vals = [3,4,6,7]
print(id(vals))

val_tensor = torch.tensor(vals)
print(id(val_tensor))

5082185600
5082080816


In [27]:
#The default data type in torch is float32
print(r.dtype)

#The one created from integers has int64
print(val_tensor.dtype)

torch.float32
torch.int64


## Converting one tensor type to another:

The most common cause for pytorch errors:
1. Tensors are of incorrect datatype
2. Tensors are not of the right shape
3. Tensors are not on the right device.

In [29]:
default_tensor_type = torch.rand(size=(3,4), dtype=None)
print(default_tensor_type)
print(default_tensor_type.dtype)

tensor([[0.5182, 0.5741, 0.7825, 0.0019],
        [0.2760, 0.1158, 0.9120, 0.1505],
        [0.3776, 0.3321, 0.3307, 0.8383]])
torch.float32


In [30]:
#Converting the default type to a float16

float_16 = default_tensor_type.type(torch.float16)
print(float_16)
print(float_16.dtype)

tensor([[0.5181, 0.5742, 0.7827, 0.0019],
        [0.2759, 0.1158, 0.9121, 0.1505],
        [0.3777, 0.3320, 0.3308, 0.8384]], dtype=torch.float16)
torch.float16


In [31]:
#How to check the parameters which cause these errors:

print(f"The dtype of tensor: {float_16.dtype}")
print(f"The shape of tensor: {float_16.shape}")
print(f"The device of tensor: {float_16.device}")

The dtype of tensor: torch.float16
The shape of tensor: torch.Size([3, 4])
The device of tensor: cpu
