In [14]:
import torch

torch.__version__

'2.1.0'

In [7]:
t = torch.zeros(2,3,4)
print(t)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [3]:
#Random tensor to check how squeeze and unsqueeze works
rand_tensor = torch.rand(3,5,4)
print(rand_tensor)
#dim 2 or 4, determines the no.of cols per row
#dim 1 or 5, determines the number of rows constituting the matrix
#dim 0 or 3 , determines the number of matrices we want in total.

tensor([[[0.6661, 0.4469, 0.5711, 0.0655],
         [0.5287, 0.5702, 0.2937, 0.9976],
         [0.9836, 0.0779, 0.4422, 0.1843],
         [0.3270, 0.5566, 0.7321, 0.5062],
         [0.5818, 0.9609, 0.8674, 0.8648]],

        [[0.6992, 0.5041, 0.7831, 0.5359],
         [0.8963, 0.2904, 0.3031, 0.7595],
         [0.9245, 0.7881, 0.0952, 0.8457],
         [0.5469, 0.1698, 0.5924, 0.1169],
         [0.9770, 0.5414, 0.9540, 0.4662]],

        [[0.3470, 0.3516, 0.6113, 0.5772],
         [0.8412, 0.8051, 0.4313, 0.4569],
         [0.8112, 0.4118, 0.6283, 0.8895],
         [0.6296, 0.6117, 0.3958, 0.9092],
         [0.2391, 0.9337, 0.6311, 0.5187]]])


In [4]:
print(rand_tensor[2][1][0])

tensor(0.8412)


In [8]:
#Adding another dimension along dim 1 or 5, notice the extra bracket on each matrix
r = torch.unsqueeze(rand_tensor,1)
print("unsqueezed:")
print(r)

print("Squeezed")
print(torch.squeeze(r,1))

unsqueezed:
tensor([[[[0.6661, 0.4469, 0.5711, 0.0655],
          [0.5287, 0.5702, 0.2937, 0.9976],
          [0.9836, 0.0779, 0.4422, 0.1843],
          [0.3270, 0.5566, 0.7321, 0.5062],
          [0.5818, 0.9609, 0.8674, 0.8648]]],


        [[[0.6992, 0.5041, 0.7831, 0.5359],
          [0.8963, 0.2904, 0.3031, 0.7595],
          [0.9245, 0.7881, 0.0952, 0.8457],
          [0.5469, 0.1698, 0.5924, 0.1169],
          [0.9770, 0.5414, 0.9540, 0.4662]]],


        [[[0.3470, 0.3516, 0.6113, 0.5772],
          [0.8412, 0.8051, 0.4313, 0.4569],
          [0.8112, 0.4118, 0.6283, 0.8895],
          [0.6296, 0.6117, 0.3958, 0.9092],
          [0.2391, 0.9337, 0.6311, 0.5187]]]])
Squeezed
tensor([[[0.6661, 0.4469, 0.5711, 0.0655],
         [0.5287, 0.5702, 0.2937, 0.9976],
         [0.9836, 0.0779, 0.4422, 0.1843],
         [0.3270, 0.5566, 0.7321, 0.5062],
         [0.5818, 0.9609, 0.8674, 0.8648]],

        [[0.6992, 0.5041, 0.7831, 0.5359],
         [0.8963, 0.2904, 0.3031, 0.7595],
     

In [11]:
#Adding another dimension along dim 2 or 4, notice the extra bracket on each matrix row
k = torch.unsqueeze(rand_tensor,2)
print("unsqueezed:")
print(k)

print("Squeezed")
print(torch.squeeze(k,2))

unsqueezed:
tensor([[[[0.6661, 0.4469, 0.5711, 0.0655]],

         [[0.5287, 0.5702, 0.2937, 0.9976]],

         [[0.9836, 0.0779, 0.4422, 0.1843]],

         [[0.3270, 0.5566, 0.7321, 0.5062]],

         [[0.5818, 0.9609, 0.8674, 0.8648]]],


        [[[0.6992, 0.5041, 0.7831, 0.5359]],

         [[0.8963, 0.2904, 0.3031, 0.7595]],

         [[0.9245, 0.7881, 0.0952, 0.8457]],

         [[0.5469, 0.1698, 0.5924, 0.1169]],

         [[0.9770, 0.5414, 0.9540, 0.4662]]],


        [[[0.3470, 0.3516, 0.6113, 0.5772]],

         [[0.8412, 0.8051, 0.4313, 0.4569]],

         [[0.8112, 0.4118, 0.6283, 0.8895]],

         [[0.6296, 0.6117, 0.3958, 0.9092]],

         [[0.2391, 0.9337, 0.6311, 0.5187]]]])
Squeezed
tensor([[[0.6661, 0.4469, 0.5711, 0.0655],
         [0.5287, 0.5702, 0.2937, 0.9976],
         [0.9836, 0.0779, 0.4422, 0.1843],
         [0.3270, 0.5566, 0.7321, 0.5062],
         [0.5818, 0.9609, 0.8674, 0.8648]],

        [[0.6992, 0.5041, 0.7831, 0.5359],
         [0.8963, 0.2904

In [12]:
new_multi = torch.rand(3,2,2,5,6)
print(new_multi)

tensor([[[[[0.1393, 0.0265, 0.6935, 0.9394, 0.0016, 0.5979],
           [0.9426, 0.3148, 0.3197, 0.7497, 0.7199, 0.2199],
           [0.1565, 0.3567, 0.4162, 0.6221, 0.9296, 0.6082],
           [0.8870, 0.0554, 0.8134, 0.9872, 0.9826, 0.3506],
           [0.9068, 0.9831, 0.0255, 0.3592, 0.4633, 0.0466]],

          [[0.1482, 0.0563, 0.6582, 0.6962, 0.9950, 0.6101],
           [0.6754, 0.1809, 0.2183, 0.8058, 0.9008, 0.9549],
           [0.8611, 0.5473, 0.7921, 0.0296, 0.2463, 0.3207],
           [0.3681, 0.5508, 0.2525, 0.1379, 0.2719, 0.3776],
           [0.1431, 0.8424, 0.2052, 0.1540, 0.7404, 0.4732]]],


         [[[0.4331, 0.1113, 0.6408, 0.8401, 0.7864, 0.4320],
           [0.6712, 0.2434, 0.0734, 0.1536, 0.4209, 0.6564],
           [0.5659, 0.1990, 0.2796, 0.1061, 0.8948, 0.2214],
           [0.5520, 0.4114, 0.5505, 0.8338, 0.9103, 0.0924],
           [0.9755, 0.2489, 0.6134, 0.7513, 0.2908, 0.5480]],

          [[0.1002, 0.3093, 0.9528, 0.3961, 0.7255, 0.9272],
           [0.08

In [8]:
torch.manual_seed(768)


In [9]:
r = torch.rand(3,4)
r2 = torch.rand(3,4)

In [10]:
print(r)
print(r2)

tensor([[0.9827, 0.1657, 0.4688, 0.6988],
        [0.8622, 0.0763, 0.0937, 0.6115],
        [0.4748, 0.3492, 0.1464, 0.9127]])
tensor([[0.5522, 0.1142, 0.8497, 0.6751],
        [0.5858, 0.1434, 0.3115, 0.1251],
        [0.4849, 0.3378, 0.3834, 0.0108]])


In [11]:
torch.manual_seed(768)
r3 = torch.rand(3,4)
r4 = torch.rand(3,4)

print(r3)
print(r4)

tensor([[0.9827, 0.1657, 0.4688, 0.6988],
        [0.8622, 0.0763, 0.0937, 0.6115],
        [0.4748, 0.3492, 0.1464, 0.9127]])
tensor([[0.5522, 0.1142, 0.8497, 0.6751],
        [0.5858, 0.1434, 0.3115, 0.1251],
        [0.4849, 0.3378, 0.3834, 0.0108]])


In [12]:
print(id(r),id(r2))

4831726000 4831728496


In [13]:
print(id(r3),id(r4))

4395906352 4831734928


In [15]:
r.dim()

2

In [16]:
r.shape()

TypeError: 'torch.Size' object is not callable

In [17]:
r.shape

torch.Size([3, 4])

In [21]:
multi_dim = torch.rand(2,3,4,5)
multi_dim.shape
multi_dim.ndim

4

In [22]:
multi_dim

tensor([[[[0.8876, 0.0582, 0.7309, 0.0427, 0.7058],
          [0.5788, 0.3605, 0.1971, 0.2515, 0.8551],
          [0.3536, 0.8667, 0.3235, 0.7239, 0.0895],
          [0.9327, 0.1189, 0.9842, 0.9028, 0.4418]],

         [[0.3228, 0.1289, 0.7725, 0.0839, 0.4225],
          [0.0651, 0.9845, 0.1520, 0.9040, 0.4994],
          [0.9057, 0.2188, 0.8337, 0.3603, 0.2706],
          [0.1558, 0.6337, 0.5682, 0.2261, 0.8841]],

         [[0.2799, 0.0399, 0.6422, 0.0577, 0.0246],
          [0.9265, 0.5851, 0.4744, 0.3165, 0.0961],
          [0.8933, 0.7144, 0.9345, 0.7588, 0.7181],
          [0.0901, 0.8411, 0.4571, 0.8156, 0.1669]]],


        [[[0.4853, 0.3305, 0.7507, 0.9261, 0.1614],
          [0.4535, 0.9071, 0.9215, 0.3729, 0.9477],
          [0.2472, 0.8259, 0.3284, 0.8506, 0.6598],
          [0.5551, 0.6201, 0.4014, 0.1175, 0.4546]],

         [[0.6148, 0.5477, 0.5799, 0.3120, 0.7705],
          [0.2714, 0.1759, 0.3447, 0.8331, 0.7973],
          [0.1136, 0.1700, 0.4861, 0.0683, 0.3890],
  

In [24]:
vals = [3,4,6,7]
print(id(vals))

val_tensor = torch.tensor(vals)
print(id(val_tensor))

5082185600
5082080816


In [27]:
#The default data type in torch is float32
print(r.dtype)

#The one created from integers has int64
print(val_tensor.dtype)

torch.float32
torch.int64


## Converting one tensor type to another:

The most common cause for pytorch errors:
1. Tensors are of incorrect datatype
2. Tensors are not of the right shape
3. Tensors are not on the right device.

In [29]:
default_tensor_type = torch.rand(size=(3,4), dtype=None)
print(default_tensor_type)
print(default_tensor_type.dtype)

tensor([[0.5182, 0.5741, 0.7825, 0.0019],
        [0.2760, 0.1158, 0.9120, 0.1505],
        [0.3776, 0.3321, 0.3307, 0.8383]])
torch.float32


In [30]:
#Converting the default type to a float16

float_16 = default_tensor_type.type(torch.float16)
print(float_16)
print(float_16.dtype)

tensor([[0.5181, 0.5742, 0.7827, 0.0019],
        [0.2759, 0.1158, 0.9121, 0.1505],
        [0.3777, 0.3320, 0.3308, 0.8384]], dtype=torch.float16)
torch.float16


In [31]:
#How to check the parameters which cause these errors:

print(f"The dtype of tensor: {float_16.dtype}")
print(f"The shape of tensor: {float_16.shape}")
print(f"The device of tensor: {float_16.device}")

The dtype of tensor: torch.float16
The shape of tensor: torch.Size([3, 4])
The device of tensor: cpu


**Working with Numpy and Pytorch**

In [3]:
import numpy as np
np.set_printoptions(precision=3)
a = [3,4,5,7]
b = np.array([9,11,12],dtype=np.int32)
tensor_a = torch.tensor(a)
tensor_b = torch.from_numpy(b)
print(tensor_a)
print(tensor_b)
print(tensor_a.shape)
print(tensor_b.shape)

tensor([3, 4, 5, 7])
tensor([ 9, 11, 12], dtype=torch.int32)
torch.Size([4])
torch.Size([3])


**More Examples of Tensor Transformation**

In [10]:
#Changing the datatype of a tensor to a desired type can be done using the .to function
tensor_b_new = tensor_b.to(torch.int16)
print(tensor_b_new)

#Transposing a tensor
print("Tensor Transpose")
t_a = torch.rand(4,5)
print(t_a)
print(t_a.shape)
print("After transpose")
t_a_tr = torch.transpose(t_a,0,1)
print(t_a_tr)
print(t_a_tr.shape, end="\n\n")

#Reshaping the tensor to a vector
print("Tensor reshape")
print("Original Tensor:")
print(t_a)
reshaped_tensor = t_a.reshape(20)
print(f"Reshaped: {reshaped_tensor} with shape {reshaped_tensor.shape}")
print(f"Original Tensor: {t_a} with shape {t_a.shape}", end="\n\n\n")

print("Working with Squeeze")

tensor([ 9, 11, 12], dtype=torch.int16)
Tensor Transpose
tensor([[0.2755, 0.7036, 0.5216, 0.4201, 0.8663],
        [0.7209, 0.2963, 0.1669, 0.0628, 0.8522],
        [0.3762, 0.9295, 0.6133, 0.1967, 0.3891],
        [0.5714, 0.6982, 0.1661, 0.6103, 0.9468]])
torch.Size([4, 5])
After transpose
tensor([[0.2755, 0.7209, 0.3762, 0.5714],
        [0.7036, 0.2963, 0.9295, 0.6982],
        [0.5216, 0.1669, 0.6133, 0.1661],
        [0.4201, 0.0628, 0.1967, 0.6103],
        [0.8663, 0.8522, 0.3891, 0.9468]])
torch.Size([5, 4])

Tensor reshape
Original Tensor:
tensor([[0.2755, 0.7036, 0.5216, 0.4201, 0.8663],
        [0.7209, 0.2963, 0.1669, 0.0628, 0.8522],
        [0.3762, 0.9295, 0.6133, 0.1967, 0.3891],
        [0.5714, 0.6982, 0.1661, 0.6103, 0.9468]])
Reshaped: tensor([0.2755, 0.7036, 0.5216, 0.4201, 0.8663, 0.7209, 0.2963, 0.1669, 0.0628,
        0.8522, 0.3762, 0.9295, 0.6133, 0.1967, 0.3891, 0.5714, 0.6982, 0.1661,
        0.6103, 0.9468]) with shape torch.Size([20])
Original Tensor: ten

*Mathematical Operations on Tensors*

In [3]:
#Let us initialize a tensor with uniform distribution, in the range[-1,1) and another which is standard normal

torch.manual_seed(43)
t1 = 2*torch.rand(2,5)-1 #torch.rand returns a uniform distribution from the range[0,1)
t2 = torch.normal(mean=0,std=1, size=(2,5))
print(f"t1:{t1}")
print(f"t2:{t2}", end="\n\n")

print("Performing element-wise multiplication")
t3 = torch.multiply(t1,t2)
print(t3)


t1:tensor([[-0.0921, -0.6070,  0.8421, -0.3076, -0.7038],
        [-0.8284,  0.1819, -0.8681,  0.4952,  0.2506]])
t2:tensor([[-0.5737, -0.0491, -0.3240,  0.9927, -0.4124],
        [-1.9310, -0.2797, -0.1837, -2.1295, -0.0045]])

Performing element-wise multiplication
tensor([[ 5.2817e-02,  2.9816e-02, -2.7285e-01, -3.0541e-01,  2.9023e-01],
        [ 1.5996e+00, -5.0876e-02,  1.5951e-01, -1.0545e+00, -1.1305e-03]])


In [10]:
from torch.utils.data import DataLoader
t = torch.arange(10, dtype=torch.int32)
print(t)
data_loader_batch = DataLoader(t, batch_size=4, drop_last=False)
data_loader = DataLoader(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [13]:
for item in data_loader:
    print(item)

for i, batch in enumerate(data_loader_batch,start=0):
    print(f"batch:{i}:{batch}")

tensor([0], dtype=torch.int32)
tensor([1], dtype=torch.int32)
tensor([2], dtype=torch.int32)
tensor([3], dtype=torch.int32)
tensor([4], dtype=torch.int32)
tensor([5], dtype=torch.int32)
tensor([6], dtype=torch.int32)
tensor([7], dtype=torch.int32)
tensor([8], dtype=torch.int32)
tensor([9], dtype=torch.int32)
batch:0:tensor([0, 1, 2, 3], dtype=torch.int32)
batch:1:tensor([4, 5, 6, 7], dtype=torch.int32)
batch:2:tensor([8, 9], dtype=torch.int32)


In [15]:
k = [(torch.rand(6), torch.rand(1)) for _ in range(2)]
print(k)

[(tensor([0.3490, 0.0966, 0.1141, 0.8013, 0.4495, 0.7612]), tensor([0.1200])), (tensor([0.9413, 0.6572, 0.4698, 0.2889, 0.4140, 0.1500]), tensor([0.0763]))]
